name: mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0

  # icon
  cupertino_icons: ^1.0.8

  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.12.0
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.4
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  http: ^1.6.0
  flutter_secure_storage: 10.0.0
  flutter_map_tile_caching: 10.1.1
  dio: 5.9.0
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Icons assets
  assets:
    - assets/images/
    - assets/fonts/
    - .env
